### ISSUE TITLE
solver step with external data test

### ISSUE THREAD

**Issue by artem-chupryna** [fossilfree/numerous#144]
there are no tests for event_id=SolveEvent.ExternalDataUpdate case  in numerous_solver.solver_step.

**Comment by artem-chupryna** [comment]
https://github.com/fossilfree/numerous/pull/145

**Comment by miamirov-teracloud** [comment]
https://github.com/fossilfree/numerous/pull/150
https://github.com/fossilfree/numerous/pull/159
