### ISSUE TITLE
vars_ordered_values is both numpy array and dict

### ISSUE THREAD

**Issue by mrdobalina2k** [fossilfree/numerous#55]
in model.py self.vars_ordered_values is first assigned as a numpy array, and then later lower_model_codegen() it's changed into a dict. This causes confusion for linting, as well as for the user/developer.

**Comment by artem-chupryna** [comment]
Fixed in https://github.com/fossilfree/numerous/commit/9c3e6ba0933ba1a26db4c9639c13542295449d4b
